#!/usr/bin/env bash

# Titulo: Post-install para Sway en Archlinux
# Autor: Hector Iván Vega Zamudio
# Correo: mxhectorvega@gmail.com
# Link: https://github.com/mxhectorvega
# Versión:v9.0
# Fecha de actualización 12/06/2022
# Nota: El sistema de preferencia tuvo que haber sido instalado con la herramienta archinstall del liveUSB,
# Seleccionando el perfil Sway con todos los controladores de código abierto.

# Instalacion de Dependencias
clear 
printf '\n \Instalando las dependencias necesarias ¯\_( ͡❛ ʖ ͡❛)_/¯\n'
sleep 1 
sudo apt install -y git firefox rofi polybar nitrogen sxhkd bspwm compton pcmanfm 
mkdir Wezterm && cd Wezterm && curl -LO https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly.Debian11.deb
sudo dpkg -i  wezterm-nightly.Debian11.deb

# Cambiando los archivos principales de BSPWM

printf '\n \Cambiando los archivos de BSPWM, Polybar, Sxhkd, \n'
git clone https://github.com/DarlezSec/dotfiles
rm .config/bspwm/bspwmrc
cd /dotfiles/.config/bspwm
mv bspwmrc ../../../
cd --
mv bspwmrc .config/bspwm/
cd .config/polybar
sudo rm  -rf * 
cd --
cd dotfiles/.config/polyvar
mv config ../../../
cd --
mv config .config/polybar
mkdir .fonts
cd .fonts
cp ../dotfiles/.fonts/* .
cd --
cp dotfiles/.xinitrc .
mkdir favoritos && cp dotfiles/font.jpg favoritos/
cp dotfiles/.config/wezterm/wezterm.lua .
mv wezterm .config/wezterm/
cp dotfiles/.config/sxhkd/sxhkdrc .
mv sxhkdrc .config/sxhkd
chmod +x .config/sxhkd/sxhkdrc
chmod +x .config/bspwm/bspwmrc
chmod +x .xinitrc
